name: mdns_responder_ffi
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  async: ^2.9.0
  ffi: ^1.1.2
dev_dependencies: 
  ffigen: ^4.1.3
  lints: ^1.0.1
  test: ^1.20.2
