name: bonjour_ffi
description: Dart bindings to event based dns_sd.h headers.
version: 0.0.5
homepage: 'https://github.com/Piero512/bonjour_ffi.git'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  async: ^2.9.0
  ffi: ^1.1.2
  json_annotation: ^4.4.0
dev_dependencies: 
  build_runner: ^2.1.10
  ffigen: ^4.1.3
  json_serializable: ^6.1.6
  lints: ^1.0.1
  test: ^1.20.2

ffigen:
  output: 'lib/ffi/bonjour_bindings.dart'
  headers:
    entry-points:
      - 'src/msgport_adapter.h'
    include-directives:
      - 'src/msgport_adapter.h'
  name: 'BonjourAdapterBindings'
  description: 'Bindings to a C++ lightweight binding to dns_sd.h'
  preamble: '// ignore_for_file: camel_case_types, non_constant_identifier_names'
  compiler-opts:
    - "-I cmake-build-debug/libuv-install/include"
    - "-I build/libuv-install/include"